import Head from 'next/head'
import React, {useEffect, useState} from "react";
import {initMonster, initMonsterWithSkill, mixMonster, replaceSkill} from "@/src/libs/monster";
import {unique} from "@/src/utils";
import Container from "@/src/components/Container";

const skillData: Skill[] = require('@/src/data/skill.json')
const monsterData: MonsterInintail[] = require('@/src/data/monster.json')

export default function Home() {
  const [m1, setM1] = useState<Monster>(initMonster("2399"))
  const [m2, setM2] = useState<Monster>(initMonster("2036"))
  const [m3, setM3] = useState<Monster>()

  const [m1Skill1, setM1Skill1] = useState<string>(skillData[0].id)
  const [m2Skill1, setM2Skill1] = useState<string>(skillData[0].id)
  const [m3Skill1, setM3Skill1] = useState<string>(skillData[0].id)

  const [m1Skill2, setM1Skill2] = useState<string>(skillData[0].id)
  const [m2Skill2, setM2Skill2] = useState<string>(skillData[0].id)
  const [m3Skill2, setM3Skill2] = useState<string>(skillData[0].id)


  const [type1, setType1] = useState<string>("2399")
  const [type2, setType2] = useState<string>("2036")


  useEffect(() => {
    console.log(m1)
  }, [m1])

  const changeM1 = () => {
    const m = initMonster(type1)
    setM1(m)
  }

  const changeM2 = () => {
    const m = initMonster(type2)
    setM2(m)
  }

  const addM1Skill = () => {
    if (m1Skill1) {
      const m = initMonsterWithSkill(m1.mid, unique([...m1.skills, m1Skill1]))
      setM1(m)
    }
  }

  const addM2Skill = () => {
    if (m2Skill1) {
      const m = initMonsterWithSkill(m2.mid, unique([...m2.skills, m2Skill1]))
      setM2(m)
    }
  }

  const addM3Skill = () => {
    if (m3 && m3Skill1) {
      const m = initMonsterWithSkill(m3.mid, unique([...m3.skills, m3Skill1]))
      setM3(m)
    }
  }

  const replaceM1Skill = () => {
    if (m1Skill2 && m1) {
      const m = replaceSkill(m1, m1Skill2)
      setM1(m)
    }
  }

  const replaceM2Skill = () => {
    if (m2Skill2 && m2) {
      const m = replaceSkill(m2, m2Skill2)
      setM2(m)
    }
  }

  const replaceM3Skill = () => {
    if (m3Skill2 && m3) {
      const m = replaceSkill(m3, m3Skill2)
      setM3(m)
    }
  }

  const resetM1 = () => {
    if (m3) {
      setM1(m3)
    }
  }

  const resetM2 = () => {
    if (m3) {
      setM2(m3)
    }
  }

  const mix = () => {
    const m = mixMonster([m1, m2])
    setM3(m)
  }

  return (
    <div>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Container>
        <div style={{
          display: 'flex',
          gap: 20,
        }}>
          <div>
            <h1>{m1.name}</h1>
            <div style={{
              maxWidth: 4 * 40,
              minHeight: 4 * 40,
              display: 'grid',
              gridTemplateColumns: 'repeat(4, 40px)',
              gridTemplateRows: 'repeat(4, 40px)',
            }}>
              {m1.skills.map(sid => {
                const skill = skillData.find(s => s.id === sid)
                // eslint-disable-next-line @next/next/no-img-element
                return <img key={sid} src={skill?.icon} alt={skill?.name}/>
              })}
            </div>
            <button onClick={changeM1}>洗炼</button>
            <div>
              <select value={m1Skill2} onChange={e => setM1Skill2(e.target.value)}>
                {skillData.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
              </select>
              <button onClick={replaceM1Skill}>打书</button>
            </div>
            <div>
              <select value={m1Skill1} onChange={e => setM1Skill1(e.target.value)}>
                {skillData.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
              </select>
              <button onClick={addM1Skill}>添加技能</button>
            </div>
            <div>
              <select value={type1} onChange={e => setType1(e.target.value)}>
                {monsterData.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
              </select>
              <button onClick={() => {
                setM1(initMonster(type1))
              }}>选择类型</button>
            </div>
          </div>
          <div>
            <h1>{m2.name}</h1>
            <div style={{
              maxWidth: 4 * 40,
              minHeight: 4 * 40,
              display: 'grid',
              gridTemplateColumns: 'repeat(4, 40px)',
              gridTemplateRows: 'repeat(4, 40px)',
            }}>
              {m2.skills.map(sid => {
                const skill = skillData.find(s => s.id === sid)
                // eslint-disable-next-line @next/next/no-img-element
                return <img key={sid} src={skill?.icon} alt={skill?.name}/>
              })}
            </div>
            <button onClick={changeM2}>洗炼</button>
            <div>
              <select value={m2Skill2} onChange={e => setM2Skill2(e.target.value)}>
                {skillData.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
              </select>
              <button onClick={replaceM2Skill}>打书</button>
            </div>
            <div>
              <select value={m2Skill1} onChange={e => setM2Skill1(e.target.value)}>
                {skillData.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
              </select>
              <button onClick={addM2Skill}>添加技能</button>
            </div>

            <div>
              <select value={type2} onChange={e => setType2(e.target.value)}>
                {monsterData.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
              </select>
              <button onClick={() => {
                setM2(initMonster(type2))
              }}>选择类型</button>
            </div>
          </div>
        </div>
        <div style={{
          display: 'flex',
        }}>
          <div style={{marginTop: 20}}>
            <button onClick={mix}>合宠</button>
            {m3 && (
              <div>
                <h1>{m3.name}</h1>
                <p>{m3.wild ? '野生' : '宝宝'}</p>
                <div style={{
                  maxWidth: 4 * 40,
                  minHeight: 4 * 40,
                  display: 'grid',
                  gridTemplateColumns: 'repeat(4, 40px)',
                  gridTemplateRows: 'repeat(4, 40px)',
                }}>
                  {m3.skills.map(sid => {
                    const skill = skillData.find(s => s.id === sid)
                    // eslint-disable-next-line @next/next/no-img-element
                    return <img key={sid} src={skill?.icon} alt={skill?.name}/>
                  })}
                </div>
                <div>
                  <select value={m3Skill2} onChange={e => setM3Skill2(e.target.value)}>
                    {skillData.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
                  </select>
                  <button onClick={replaceM3Skill}>打书</button>
                </div>
                <div>
                  <select value={m3Skill1} onChange={e => setM3Skill1(e.target.value)}>
                    {skillData.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
                  </select>
                  <button onClick={addM3Skill}>添加技能</button>
                </div>
                <div>
                  <button onClick={resetM1}>替换1</button>
                  <button onClick={resetM2}>替换2</button>
                </div>
              </div>
            )}
          </div>
        </div>
      </Container>
    </div>
  )
}
