import Head from 'next/head'
import React, {useEffect, useState} from "react";
import {initMonster, mixMonster} from "@/src/libs/monster";
import WindowWrapper from "@/src/components/window-wrapper";
import {getRateLevel} from "@/src/utils";
import {MIX_MONSTER_SKILL_NUM_RATE} from "@/src/config/constant";

const skillData: Skill[] = require('@/src/data/skill.json')

export default function Home() {
	const [m1, setM1] = useState<Monster>(initMonster(2))
	const [m2, setM2] = useState<Monster>(initMonster(3))
	const [m3, setM3] = useState<Monster>()

  useEffect(() => {
    const map = new Map<number, number>()
    for (let i = 0; i < 10000; i++) {
      const level = getRateLevel(MIX_MONSTER_SKILL_NUM_RATE)
      const strLevel = level * 10 + 1
      if (map.has(strLevel)) {
        const num = map.get(strLevel) || 0
        map.set(strLevel, num + 1)
      } else {
        map.set(strLevel, 1)
      }
    }
    const arr = Array.from(map.entries())
    console.log('技能数量概率')
    arr.sort((a, b) => a[0] - b[0]).forEach(([level, num]) => {
      console.log(`${level}级：${num / 10000}, 3+1=${Math.round(((level-1) / 10) * (3 + 1))}}`)
    })
  }, [])

	const changeM1 = () => {
		const m = initMonster(2)
		setM1(m)
	}

	const changeM2 = () => {
		const m = initMonster(3)
		setM2(m)
	}

	const mix = () => {
		const m = mixMonster([m1, m2])
		setM3(m)
	}

	return (
		<div>
			<Head>
				<title>Test</title>
				<meta name="description" content="Generated by create next app"/>
				<meta name="viewport" content="width=device-width, initial-scale=1"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>
            <WindowWrapper>
                <div style={{
                    display: 'flex',
                    gap: 20,
                }}>
                    <div>
                        <h1>{m1.name}</h1>
                        <div style={{
                            margin: '0 auto',
                            maxWidth: 4 * 40,
                            minHeight: 4 * 40,
                            display: 'grid',
                            gridTemplateColumns: 'repeat(4, 40px)',
                            gridTemplateRows: 'repeat(4, 40px)',
                        }}>
                            {m1.skills.map(sid => {
                                const skill = skillData.find(s => s.id === sid)
                                // eslint-disable-next-line @next/next/no-img-element
                                return <img key={sid} src={skill?.icon} alt={skill?.name}/>
                            })}
                        </div>
                        <button onClick={changeM1}>洗炼</button>
                    </div>
                    <div>
                        <h1>{m2.name}</h1>
                        <div style={{
                            margin: '0 auto',
                            maxWidth: 4 * 40,
                            minHeight: 4 * 40,
                            display: 'grid',
                            gridTemplateColumns: 'repeat(4, 40px)',
                            gridTemplateRows: 'repeat(4, 40px)',
                        }}>
                            {m2.skills.map(sid => {
                                const skill = skillData.find(s => s.id === sid)
                                // eslint-disable-next-line @next/next/no-img-element
                                return <img key={sid} src={skill?.icon} alt={skill?.name}/>
                            })}
                        </div>
                        <button onClick={changeM2}>洗炼</button>
                    </div>
                </div>
                <div style={{
                    display: 'flex',
                }}>
                    <div style={{marginTop: 20}}>
                        <button onClick={mix}>合宠</button>
                        {m3 && (
                            <div>
                                <h1>{m3.name}</h1>
                                <p>{m3.wild ? '野生' : '宝宝'}</p>
                                <div style={{
                                    margin: '0 auto',
                                    maxWidth: 4 * 40,
                                    minHeight: 4 * 40,
                                    display: 'grid',
                                    gridTemplateColumns: 'repeat(4, 40px)',
                                    gridTemplateRows: 'repeat(4, 40px)',
                                }}>
                                    {m3.skills.map(sid => {
                                        const skill = skillData.find(s => s.id === sid)
                                        // eslint-disable-next-line @next/next/no-img-element
                                        return <img key={sid} src={skill?.icon} alt={skill?.name}/>
                                    })}
                                </div>
                            </div>
                        )}
                    </div>
                </div>
            </WindowWrapper>
		</div>
	)
}
